### ISSUE TITLE
compression_codec config param doesn't work

### ISSUE THREAD

**Issue by mainameiz** [zendesk/delivery_boy#11]
https://github.com/zendesk/delivery_boy/blob/master/lib/delivery_boy/instance.rb#L87

It must be `Symbol`, not a `String`.

**Comment by mensfeld** [comment]
@mainameiz so is it working as a symbol, or is it not working at all?

**Comment by mainameiz** [comment]
@mensfeld it is working with symbol

**Comment by mensfeld** [comment]
@mainameiz  so it doesn't seem to be a bug. This states as it needs to be a symbol as well: https://github.com/zendesk/ruby-kafka#compression

**Comment by mainameiz** [comment]
@mensfeld https://github.com/zendesk/ruby-kafka/blob/v0.4.2/lib/kafka/compression.rb#L10
it is expeced to a symbol

**Comment by mensfeld** [comment]
@mainameiz so I totally don't get what is the problem 0_0

**Comment by mainameiz** [comment]
@mensfeld 
https://github.com/zendesk/delivery_boy/blob/master/lib/delivery_boy/config.rb#L30
It's a string by default

**Comment by mensfeld** [comment]
@mainameiz I get it now. Couldn't understand as your description is a big enigmatic.

**Comment by mainameiz** [comment]
:smiley:

**Comment by dasch** [comment]
Fixed by #12
