### ISSUE TITLE
Support for SASL SCRAM

### ISSUE THREAD

**Issue by mensfeld** [zendesk/delivery_boy#13]
It seems ruby-kafka 0.5.1 supports now SCRAM, would be nice to have it as well in the delivery boy.

**Comment by dasch** [comment]
Since that support is only in v0.5.1, it would require having a minimal dependency on that version, removing support for Kafka 0.9. So I'm a bit wary about doing that.

Is this a feature that is heavily used?

**Comment by mensfeld** [comment]
@dasch well I use it :D and to be honest I though that delivery boy would allow same initialization options as ruby-kafka. Can't we just detect the version and act upon it with set of settings as SCRAM settings are either way optional for kafka object initialization.

**Comment by dasch** [comment]
Hmm. I'll try to take a look at this next week. It wouldn't be completely unreasonable for DB to target the current active ruby-kafka release series. It's been quite a while since Kafka 0.10 came out.

**Comment by mensfeld** [comment]
@dasch there's a 1.0 already and as far as I remember you guys are 0.10+ as well, so I guess it wouldn't be that bad. For 0.8 there's still unmaintained poseidon :rocket:  hehe
