### ISSUE TITLE
Testing "inline" such that messages are produced and consumed from memory

### ISSUE THREAD

**Issue by rmontgomery429** [zendesk/delivery_boy#14]
I'm using DeliveryBoy and Racecar to produce messages and consume them from the same app. I'm using `require 'delivery_boy/rspec'` to store the message in memory. I'm trying to determine the best way to consumer those message. 

This works:

```ruby
message = DeliveryBoy.testing.messages_for("topicA").first
TopicAConsumer.new.process(message)
```

However... we're using the offset of the message in the consumer which `DeliveryBoy::Fake::FakeMessage` doesn't seem to provide. So now we do this:

```ruby
message = DeliveryBoy.testing.messages_for("topicA").first
TopicAConsumer.new.process(OpenStruct.new(offset: 1, partition: message.partition, topic: message.topic, value: message.value))
```

This also works but I'm hoping to find a better way to avoid having to do this in every case. I'm not sure if this is just crossing the streams and I'm doing it wrong but this seems like there's something missing here. Now, should DeliveryBoy know about Racecar? Doesn't seem like it... but should a DeliveryBoy Fake Message know about an offset... maayybbee? `¯\_(ツ)_/¯`

Thoughts?

**Comment by dasch** [comment]
Can you add offsets to messages in a PR?
