### ISSUE TITLE
API inconsistency between ruby-kafka and delivery boy for compression and timeouts

### ISSUE THREAD

**Issue by mensfeld** [zendesk/delivery_boy#21]
delivery boy requires compression_codec to be a string while ruby-kafka docs say that it should be a symbol (in the docs).

I really don't find any reason why delivery boy does not accept symbolized version when it is the default one for ruby-kafka...

same for timeouts - float is allowed by ruby-kafka but not by delivery boy

**Comment by dasch** [comment]
It's simply because DB is geared towards using external configuration (YAML or ENV vars). I would be open to making things more flexible, but I'm not sure it's entirely needed – most people should not use ruby-kafka directly.

**Comment by mensfeld** [comment]
My point is in the inconsistency that for me as a gem maintainer causes some problems as I have to support both - ruby-kafka format for karafka and delivery_boy format for waterdrop - despite the fact that both are based on ruby-kafka underneath.

**Comment by dasch** [comment]
As for the symbol – can you do a PR implementing support for symbols in KingKonf? Since they're garbage collected in recent versions of Ruby, it should be safe to allow them.

**Comment by mensfeld** [comment]
@dasch no problem. Will do that during the weekend.

**Comment by dasch** [comment]
Thanks!
