### ISSUE TITLE
Multiple brokers support

### ISSUE THREAD

**Issue by empeje** [zendesk/delivery_boy#26]
I have a use case to use the delivery boy to send to different Kafka broker for each specific feature. Would be nice if it supported.

**Comment by dasch** [comment]
Do you mean different clusters?

**Comment by empeje** [comment]
yes @dasch

**Comment by dasch** [comment]
In that case, no: DeliveryBoy is specifically tailored to simple setups. It's quite easy to replicate the functionality using raw ruby-kafka, though.

**Comment by empeje** [comment]
Thanks @dasch
