### ISSUE TITLE
Rspec Fake missing header keyword

### ISSUE THREAD

**Issue by GabrielGLevine** [zendesk/delivery_boy#43]
The [Fake class](https://github.com/zendesk/delivery_boy/blob/master/lib/delivery_boy/fake.rb) that is used for Rspec testing does not support the "headers" keyword which is supported by the `deliver` and `deliver_async` apis and which causes implementations that make use of headers to fail when using `delivery_boy/rspec`. Can you please add "headers" as a valid argument to the mock?

**Comment by ryantownsend** [comment]
@GabrielGLevine I've opened a PR to address this: https://github.com/zendesk/delivery_boy/pull/47
