### ISSUE TITLE
Are there plans to switch from ruby-kafka to rdkafka-ruby? 

### ISSUE THREAD

**Issue by kyle-owen-opendoor** [zendesk/delivery_boy#62]
I saw that the racecar gem switched from using ruby-kafka to rdkafka-ruby and was wondering if there were any plans to migrate delivery_boy as well? It would be nice to be able to use racecar and delivery_boy without needing to install both ruby-kafka and rdkafka-ruby

**Comment by fragkakis** [comment]
I think this should be reopened, [ruby-kafka](https://github.com/zendesk/ruby-kafka) has a deprecation notice.
