### ISSUE TITLE
Error loading delivery_boy yaml file

### ISSUE THREAD

**Issue by night91** [zendesk/delivery_boy#67]
Unknown alias: defaults (Psych::BadAlias)

This happens because Psych 3 => 4, doesn't allow aliases by default.

KingKonf::ConfigFileLoader uses: `data = YAML.load(template.result(binding))`

This now needs the aliases enabled `YAML.load(aliases: true)` or to use `YAML.unsafe_load`.

Ruby version: 3.1.1

**Comment by zhchsf** [comment]
same error, Ruby 3.0.4 and 3.1.2

**Comment by dasch** [comment]
You should be able to upgrade `king_konf` to version `1.0.1` now; does that fix the issue?
