### ISSUE TITLE
Possibility to configure delivery boy via DSL

### ISSUE THREAD

**Issue by mensfeld** [zendesk/delivery_boy#7]
I see that there's a YAML based option and ENV variables, but would it be possible to configure delivery boy via Ruby settings?

**Comment by dasch** [comment]
Which options would you like to configure, or do you just have a general preference for configuring with Ruby?

**Comment by mensfeld** [comment]
Well the case is that I have a dry configuration as an object and I would love to be able to propagate all the settings from it. I could overwrite ENV stuff but it does not feel natural to me.

**Comment by dasch** [comment]
OK, I'll take a look. I'll probably just load `config/delivery_boy.rb` if it's present.

**Comment by mensfeld** [comment]
Well I would appreciate a possibiltiy to configure it from wherever I want. For a single file sinatra app setup I may not have a config directory at all :D

**Comment by dasch** [comment]
Every configuration option is available as a getter/setter pair on the Config instance, courtesy of [KingKonf](https://github.com/dasch/king_konf).

**Comment by mensfeld** [comment]
Great :) too bad you didn't decide to go with dry validations and dry types - would be one gem less to maintain. Thank you. I will investigate further.
