### ISSUE TITLE
Possibility to provide partition and partition key when sending

### ISSUE THREAD

**Issue by mensfeld** [zendesk/delivery_boy#8]
I don't see that in docs, but is it (or will it) be possible to provide partition key and/or partition when sending messages?

**Comment by dasch** [comment]
Yup, you can provide the exact same options as you can to `produce` in ruby-kafka. I can expand a bit on it in the README, although I'd prefer to keep this library beginner-friendly.

**Comment by mensfeld** [comment]
Thanks :-)

**Comment by dasch** [comment]
np :)

I've documented the options in the README.
